### PR TITLE
Fix crash from missing operationExecutor in OperationModelStore create

### LINKED ISSUE #1814: [Bug]: Crash on 5.0.0 - "Unrecognized operation: login-user-from-subscription"
### What happened?

I see crash on few devices (Android 11 and 10 for sure).
This is on calling `OneSignal.initWithContext()`

### Steps to reproduce?

```Markdown
-
```

### What did you expect to happen?

-

### OneSignal Android SDK version

5.0.0

### Android version

11, 10

### Specific Android models

```Markdown
* Galaxy A31
* Galaxy A7 (2018)
* Galaxy S9+
* Moto G(9) Plus
* Nokia 9
```

### Relevant log output

```Shell
Stacktrace:

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:90)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:83)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$core_release(ServiceProvider.kt:40)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:197)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
       at pl.tajchert.canary.CanaryApp.onCreate(CanaryApp.kt:66)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.Exception: Unrecognized operation: login-user-from-subscription
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:58)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:27)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:129)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.<init>(OperationModelStore.kt:30)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:90)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:83)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$core_release(ServiceProvider.kt:40)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:197)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
       at pl.tajchert.canary.CanaryApp.onCreate(CanaryApp.kt:66)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<!-- probot = {"onesignal-probot":{"response_time_in_business_days":1}} -->

### PR DESCRIPTION
**Pull request by emawby**
I removed throwing from create for non-singleton model stores. I kept throw if a singleton model store is unable to create its model.

# Description
## One Line Summary
Fix a crash when the login user from subscription operation is being read from the cache.

## Details
fixes #1814 
The OperationModelStore did not account for the `LoginUserFromSubscriptionOperation` operation when creating operations from JSON and would throw an exception.

This create method can no longer throw an exception even if it doesn't find the operation.

### Motivation
Fix crash

### Scope
cached login operation

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
Tested on a physical device.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1845)

### CODE REVIEW

File: OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/internal/operations/impl/OperationModelStore.kt [hunk 1]
```diff
@@ -48,14 +53,15 @@ internal class OperationModelStore(prefs: IPreferencesService) : ModelStore<Oper
...
             LoginUserOperationExecutor.LOGIN_USER -> LoginUserOperation()
+            LoginUserFromSubscriptionOperationExecutor.LOGIN_USER_FROM_SUBSCRIPTION_USER -> LoginUserFromSubscriptionOperation()
             RefreshUserOperationExecutor.REFRESH_USER -> RefreshUserOperation()
             UpdateUserOperationExecutor.SET_TAG -> SetTagOperation()
             UpdateUserOperationExecutor.DELETE_TAG -> DeleteTagOperation()
             UpdateUserOperationExecutor.SET_PROPERTY -> SetPropertyOperation()
             UpdateUserOperationExecutor.TRACK_SESSION_START -> TrackSessionStartOperation()
             UpdateUserOperationExecutor.TRACK_SESSION_END -> TrackSessionEndOperation()
             UpdateUserOperationExecutor.TRACK_PURCHASE -> TrackPurchaseOperation()
-            else -> throw Exception("Unrecognized operation: $operationName")
```
Comment (jkasten2) [inline OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/internal/operations/impl/OperationModelStore.kt:58]: I think we should still throw, otherwise it will make finding the root cause much harder later.

**Review by jkasten2 — CHANGES_REQUESTED** [review]

File: OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/internal/operations/impl/OperationModelStore.kt (hunk 1 above)
Comment (emawby) [reply OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/internal/operations/impl/OperationModelStore.kt]: Agreed I reverted this change

**Review by jkasten2 — APPROVED** [review]
